### ISSUE TITLE
[ISSUE] Garage Update

### ISSUE THREAD

**Issue by masonschafercodes** [Renewed-Scripts/qb-phone#101]
phone needs to updated to support the latest version qb-garages update, commit can be found here: [update](https://github.com/qbcore-framework/qb-garages/commit/54023964bcd414a129e7f99bd702bd3b2f1ac007#diff-437dcbdcefbb257379ec6d95c6877f5f4feb823b3c5d920b643f9aeebcad7db0)

The config has changed and breaks the garages on the phone.

**Comment by paruthepro** [comment]
Update was pushed recently, please test it, should be all good now though, works on a fresh install!

**Comment by ItzAtoy** [comment]
Im still having troubles after i updated my phone, any ideas?

**Comment by Soldierofthelam** [comment]
same issues garage not working

**Comment by paruthepro** [comment]
```
RegisterNetEvent('qb-phone:client:updateGarages', function()
    SendNUIMessage({
        action = "UpdateGarages",
    })
end)
```

Replace line 57 with the above code.

**Comment by ItzAtoy** [comment]
> RegisterNetEvent('qb-phone:client:updateGarages', function()
>     SendNUIMessage({
>         action = "UpdateGarages",
>     })
> end)

That's the same code that's already there
![image](https://user-images.githubusercontent.com/79236772/221737370-de52d536-0c4c-4769-be12-cf93e6b75feb.png)

**Comment by paruthepro** [comment]
> 

If that's the case then you are either not using qb-garages or are using outdated qb-garages, the exports work fine, I am using my version of qb-garages (Job garages, gang garages and some player run business garages added) of which is 4 commits behind the main (About 2-3 weeks out of date) and works fine, if you're using a different garage script you'll need to convert the exports yourself.

**Comment by ItzAtoy** [comment]
> 

Im running QB garage and i just rebooted my whole server its a fresh build, I have no idea what could be causing this could i have messed up a step on the setup?

**Comment by itsKline** [comment]
Fixed with previous updates
