### ISSUE TITLE
Phone messages not saving properly after using an emoji 

### ISSUE THREAD

**Issue by Nootella01** [Renewed-Scripts/qb-phone#116]
![image](https://user-images.githubusercontent.com/88634875/229567464-4bb1ac75-5bb1-4916-b631-4915915b2113.png)

this happens in console after using an emoji in any text mesages.
any ideas of a fix?

**Comment by IamCodyy** [comment]
`ALTER TABLE phone_messages CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
`
Run that in your qbcore database
