### ISSUE TITLE
Restarting the phone - Jobs are Gone

### ISSUE THREAD

**Issue by Bornke** [Renewed-Scripts/qb-phone#129]
Every Time i Restart the phone, everybody loses theyr job !

**Comment by abu3baid** [comment]
same problem....

**Comment by Millusion** [comment]
> It's part of the server employments events. Think it's 'qb-phone:server:GetMyJobs' that sets it to unemployed.

Indeed that callback triggers getJobs which returns CachedJobs. If that CachedJobs table is still empty it'll set everyone to unemployed
