### ISSUE TITLE
Image errors in console

### ISSUE THREAD

**Issue by enlistedmango** [Renewed-Scripts/qb-phone#14]
Upon taking a picture with the camera, I get this error in the console.

This is during the "touching up photo" message that appears on screen.

<img width="906" alt="Code_iS5gMkbD8Z" src="https://user-images.githubusercontent.com/82413197/191345962-f4c6c348-432f-4209-a4b5-0cf7fc26b771.png">

**Comment by KrnkTV** [comment]
setup webhook in server.lua and will be fine

**Comment by MannyOnBrazzers** [comment]
Download latest, Config.WebHook has been added to the config. Input your discord webhook there
