### ISSUE TITLE
Vehicle App no longer works with new QB-Garages 2.0 

### ISSUE THREAD

**Issue by AngryMaximus** [Renewed-Scripts/qb-phone#156]
AS the title says, It returns a server error when trying to display vehicles on the app Returning a nil value for ('garage')

**Comment by QAZ-511** [comment]
> AS the title says, It returns a server error when trying to display vehicles on the app Returning a nil value for ('garage')

**Comment by AngryMaximus** [comment]
Closed, It was due to a custom re-design of QB-Garage 2.0, Was not present on a fresh QB Garage 2.0 Install
