### ISSUE TITLE
Vehicle documentation

### ISSUE THREAD

**Issue by Morji789** [Renewed-Scripts/qb-phone#16]
Vehicle documentation is not working, its just not checking for vehicles and creating documents

**Comment by KrnkTV** [comment]
![Screenshot_21](https://user-images.githubusercontent.com/82491495/191349687-74bf38c4-2a59-411d-b58a-13d5145d972a.png)
its working for me after last PR

**Comment by MannyOnBrazzers** [comment]
Issue resolved, please download latest
