### ISSUE TITLE
Hiring players through employment app.

### ISSUE THREAD

**Issue by JustUmee** [Renewed-Scripts/qb-phone#23]
When giving myself the jobs, its fine and updates the job list and role on the phone, however when I hire someone using the phone, they do not show on employee list on the phone but do have the job, they show on the phone when the script has been restarted.

**Comment by TxBUTTERxT** [comment]
I am having the same issue when trying to hire through the employment app.

**Comment by Iitsmemitchell** [comment]
This 'restart the phone to see the changes' issue is also with the Advertisement app, you post a ad and it will show after the phone script has been restarted. Same goes with discord chatrooms, make one and it doesn't show but when you restart the script it shows the discord chatroom in the app.

**Comment by gitgaming21** [comment]
iv find why this is i think the only time it don't work is when you hire some one on with grade 0 so i can made all the job in the shared list to have the first grade start at 1 and it works

**Comment by itsKline** [comment]
This has been fixed in a previous update
