### ISSUE TITLE
Suggestion: Automatic way for you to share contacts & Copy Pasta

### ISSUE THREAD

**Issue by JustUmee** [Renewed-Scripts/qb-phone#25]
Basically the title, with vanilla qb-phone you were able to share number with nearby players and it automatically pop up on contacts for you to add them, something similar would be great qol change.

Is there a way to let people highlight text/numbers in the phone for qol change so we can CTRL+C/V would make life a lot easier.

**Comment by KrnkTV** [comment]
Or can be with command /p# to show phone number into local chat

**Comment by KrnkTV** [comment]
If you want u can test this PR https://github.com/Renewed-Scripts/qb-phone/pull/27

**Comment by Swompen** [comment]
Shoulndt be to hard to do, You could also just make a document -> save it -> send it locally

**Comment by Sharkiiie** [comment]
This was one of my biggest gripes with the npstyle phone, they half disabled the suggest contact feature.
I was gonna just enable it but I didn't bother working on that phone when I saw this one in the showcase :)

**Comment by KrnkTV** [comment]
I have it done will PR later

**Comment by JustUmee** [comment]
Being able to copy and pasting in messages app would be nice too

**Comment by MannyOnBrazzers** [comment]
Download latest, this has been added : )
