### ISSUE TITLE
Unable to call players

### ISSUE THREAD

**Issue by TankinTom** [Renewed-Scripts/qb-phone#26]
When trying to dial other players, getting an error saying the person is unavailable. Text works, calling doesn't work for some reason. This is weather you do a direct dial, or dial from contacts

**Comment by Swompen** [comment]
Tested all types of calls on my server and all works, contacts, not added, via my yellow pages app etc. All works.

Any errors?

**Comment by TankinTom** [comment]
I tested everything for zoo last night on a discord call, the error that comes back for everyone is "This person is unavailable" in the phone, no errors anywhere else. Previous phone was the default phone, and worked without any issues.

**Comment by FjamZoo** [comment]
I've done a lot of testing today and I am unable to find the error please try and update your core, create a new character to see if any of those could of been the issue.

Gonna close this as it does not seem to be a phone issue.
