### ISSUE TITLE
2560x1440 Res Incompatibility

### ISSUE THREAD

**Issue by NoobySloth** [Renewed-Scripts/qb-phone#35]
The input box needs adjusting for supporting Res

![image](https://user-images.githubusercontent.com/6962192/191630440-b9f78f1d-18d8-4508-947b-2108b9ba4c8c.png)
![image](https://user-images.githubusercontent.com/6962192/191630486-7d23a86b-e762-4cee-93d9-7b37687c72b6.png)

**Comment by FjamZoo** [comment]
@MannyOnBrazzers

**Comment by rust1co** [comment]
I do have this problem aswell, but gotta be honest, 90% of UI in QBCore doesnt work at 2560x1440

**Comment by MannyOnBrazzers** [comment]
Please download latest, check if the resolution issue persists.

**Comment by SirOMGitsYOU** [comment]
![image](https://user-images.githubusercontent.com/20475516/196011542-d62ac0d1-3ccf-4aa4-911d-3dd17e7a5e3d.png)
![image](https://user-images.githubusercontent.com/20475516/196011591-a50f5b71-c0ec-4bc8-a63e-bdc7135b2b69.png)

Just downloaded today, also have a 2560x1440 monitor :( this is the only thing stopping me currently maining this phone
