### ISSUE TITLE
Bug: Texting and Timezones

### ISSUE THREAD

**Issue by JustUmee** [Renewed-Scripts/qb-phone#40]
It seems the order of texts are going based of the local time for player and not the time in the server and it messes up the order of texts, tested this after midnight in the UK texting a US person in game and their messages go under their last messages when recieved -  https://i.gyazo.com/90ab4db1f5ef41e0e369a22aa530261d.png - in the pic the messages "is it" and "beep" is the person in US and were sent after the ones in blue, should be in order.

**Comment by HBOllie** [comment]
A fix I would use on normal qb-phone was to change all getHours and getMinutes to getUTCHours and getUTCMinutes so it uses a universal timezone.

**Comment by KrnkTV** [comment]
But if you are in same timezone its okay right ?

**Comment by HBOllie** [comment]
Yh, UTC basically makes all time show your local time so everything is in order even if they are in the US. Without it someone from the US who's 6 Hours behind make it so the message would go before your reply

**Comment by FjamZoo** [comment]
> A fix I would use on normal qb-phone was to change all getHours and getMinutes to getUTCHours and getUTCMinutes so it uses a universal timezone.

I mean if you can provide such a fix for it with this phone that could use this then please do so ❤️

**Comment by FjamZoo** [comment]
This issue has now been resolved thank you for reproting
