### ISSUE TITLE
UI Issue - Changing Grade of Employee

### ISSUE THREAD

**Issue by HBOllie** [Renewed-Scripts/qb-phone#41]
If a server has quite a few ranks within a job for eg with me 11 ranks in PD - You are unable to change a player to the last few due to the list extending down to the bottom of the phone

![image](https://user-images.githubusercontent.com/10517362/191870001-1788b9f9-9180-43aa-8f8d-67b96accfd78.png)

**Comment by FjamZoo** [comment]
This has been fixed in the most recent PR pelase update
