### ISSUE TITLE
Missing dependencies and typo's

### ISSUE THREAD

**Issue by Iitsmemitchell** [Renewed-Scripts/qb-phone#45]
Dear Renewed,

While updating my qb-phone to the renewed version i found that there are a couple triggerserverevents are asking for 'renewed-debts' and 'renewed-cameras' .. Also there a event in qb-phone -> cleint -> mail.lua : `buttonEvent = "Renewed-Debt:server:AcceptShit",` but in qb-phone -> client -> debt.lua there is `TriggerServerEvent('Renewed-Debts:server:PayFull` spelled debts instead of debt ... 

Is it possible that some of these lines of code are a bit messed up and need a look over and/or we are missing some renewed scripts which are not released yet? It can also be that i am the unexperienced self called ''FiveM Dev' who just is to stupid to understand it? :kek: 

(I'm dutch, sorry for the self sarcasm, its a joke kinda)

**Comment by MannyOnBrazzers** [comment]
Those are setup for 2 scripts by Renewed which will be compatible with this phone. Please be patient, you'll see an announcement regarding those resources soon!

**Comment by Iitsmemitchell** [comment]
Appreciated the info, i wll. But i asked another question and perhabs you forget to reply on that..

>  .. Also there a event in qb-phone -> client -> mail.lua : buttonEvent = "Renewed-Debt:server:AcceptShit", but in qb-phone -> client -> debt.lua there is TriggerServerEvent('Renewed-Debts:server:PayFull spelled debts instead of debt ...

and there are alot of events saying paythefucker, hiremf etc, isn't that a bit weird tbh? Are you planning on cleaning up the code?
