### ISSUE TITLE
advertisement app needing a URL to work

### ISSUE THREAD

**Issue by Iitsmemitchell** [Renewed-Scripts/qb-phone#47]
Dear Renewed,

i found out todat that if you make an ad in the advertisement app you need to fill in a working URL link otherwise it just doesn't do anything when you hit the 'post' button other than close the prompt and display Nothing Here!.

If you fill in nothing at the URL field it will print this console error: 

`[script:qb-phone] SCRIPT ERROR: @qb-phone/server/advertisements.lua:30: attempt to index a nil value (local 'url')`

![image](https://user-images.githubusercontent.com/86323279/192100054-cc37f4de-8825-48ff-8bdc-0660ed3d4661.png)

But if you fill in a image link it works:
![image](https://user-images.githubusercontent.com/86323279/192100130-5e02f6d5-d578-4922-812b-c22c11a346af.png)

**Comment by MannyOnBrazzers** [comment]
Download latest, issue has been fixed. Thank you!
