### ISSUE TITLE
Exchange Crypto not working properly

### ISSUE THREAD

**Issue by Peple77** [Renewed-Scripts/qb-phone#48]
When I try to exchange gne it says I don't have that much crypto when im exchanging 4. 
And is there a way that I can change it to be able to exchange crypto to yourself

![image](https://user-images.githubusercontent.com/98569110/192123403-9d31752c-9705-4d3a-89cd-ba60547ce6f3.png)

**Comment by MannyOnBrazzers** [comment]
Download latest, issue for exchanging has been fixed. Visit crypto.lua in the server files to be able to see the code for exchanging with yourself. I wouldn't see why you would wanna do that but hey, do your thang.
