### ISSUE TITLE
OnDuty Toggle

### ISSUE THREAD

**Issue by balancemytires** [Renewed-Scripts/qb-phone#5]
Setting on-duty makes all apps' notification icon pop up with 0 notifications

**Comment by FjamZoo** [comment]
🙏 Gonna look into to this and see why that would occour

**Comment by balancemytires** [comment]
I believe its trying to update the phone and its not fully loaded refreshed by the time you exit the menu, its basically what happens when you open QB-Phone too early after ensuring it.

**Comment by Iitsmemitchell** [comment]
> I believe its trying to update the phone and its not fully refreshed by the time you exit the menu, its basically what happens when you open QB-Phone too early after ensuring it.

I think this also relates to the different apps not refreshing the changes you make until you restart the phone script: with the Advertisement app, you post a ad and it will show after the phone script has been restarted. Same goes with discord chatrooms, make one and it doesn't show but when you restart the script it shows the discord chatroom in the app.

**Comment by MannyOnBrazzers** [comment]
Download latest, this definetely fixed it but make sure you can receive alerts in other places. I wanna make sure I didn't get rid of the entire app alert system

**Comment by MannyOnBrazzers** [comment]
Ignore what I said above, reverted and completely fixed the issue. Download latest
