### ISSUE TITLE
Some of the jobs not showing on the app

### ISSUE THREAD

**Issue by Luceeiy** [Renewed-Scripts/qb-phone#51]
I Went through every step multiple times and jobs are not appearing on the app , i don't know if its intentionally set to have a max of 3 jobs.

![kdwEvEq](https://user-images.githubusercontent.com/91788613/192171600-bbe3525d-f3a3-44c9-8ac2-0322ad786202.png)

**Comment by Luceeiy** [comment]
I want to add to this that also when you try to pay your employee's the money goes to you and not employee's

**Comment by paruthepro** [comment]
You've not added the jobs database side most likely which will cause this issue, you may notice on login/logout your job is reset to unemployed/default job as well, this is not a bug but an issue your end, as for the paying employees i've tested it on the current version and it works fine, so again an issue your end.
