### ISSUE TITLE
Everytime I reconnect on my server my job goes back to civlian, unemplyed.

### ISSUE THREAD

**Issue by nxni21** [Renewed-Scripts/qb-phone#54]
whenever I setjob to police or ems when i reconnect or restart my server, my character's job reverts back to civilian unemployed.

**Comment by AndreasFromDanmark** [comment]
Yep getting some error
![image](https://user-images.githubusercontent.com/35656492/193417282-dace839b-419e-42c5-9966-716a10cb212c.png)

**Comment by purplecofe** [comment]
same here, any solution?

**Comment by Peple77** [comment]
I have the same issue and I followed everything in the readme, and when I add someone to a job its super delayed and when I hire them with the app I don't even think it works

**Comment by RAKSHPLAYS** [comment]
DID Any 1 Get The Solution For This Even Iam Facing This Issue

**Comment by itsKline** [comment]
This is not an issue. Please re-read the readme and follow it carefully
