### ISSUE TITLE
Vehicle registretion

### ISSUE THREAD

**Issue by Morji789** [Renewed-Scripts/qb-phone#6]
Vehicle registration doesn't show up after buying a vehicle

**Comment by KrnkTV** [comment]
Yep for me as well

**Comment by KrnkTV** [comment]
have fix with this request: https://github.com/Renewed-Scripts/qb-phone/pull/10/commits/9b2456513e47f91f756c4a94d8c35b92d34efea2

**Comment by Swompen** [comment]
As @KrnkTV says, fixed in that PR.
