### ISSUE TITLE
[Improvement/Suggestion] Move the phone out of the corner of the screen

### ISSUE THREAD

**Issue by SirOMGitsYOU** [Renewed-Scripts/qb-phone#64]
Hey, would it be possible to add a Config option or just generally move the phone a smidge out of the corner of the screen, Similarly to how the QBCore original phone is somewhat attached to the bottom of the screen with a bit of a gap, and then there is a medium-sized gap between the phone and the right side

**Comment by itsluap** [comment]
this is actually pretty simple, you can change it by going to qb-phone/html/css/main.ss and change line 39 to `right: -1.5vh;`

**Comment by itsKline** [comment]
Answer given
