### ISSUE TITLE
Employment Not Working

### ISSUE THREAD

**Issue by Captmorg21** [Renewed-Scripts/qb-phone#66]
Im having some issues with employment, ive replaced all the code from the readme, and ive generated a new player_jobs table, and its in this format:

`{"RWQ59192":{"name":"Jackson English","grade":1,"cid":"RWQ59192"},"PLL19380":{"name":"Mr  Lordd","grade":4,"cid":"PLL19380"}}`

But im getting this error when i apply for a job in the qb-cityhall

```
[     script:qb-phone] SCRIPT ERROR: @qb-phone/server/employment.lua:329: attempt to index a nil value (field 'employees')
[     script:qb-phone] > handler (@qb-cityhall/server/main.lua:121)
[  script:qb-cityhall] SCRIPT ERROR: @qb-cityhall/server/main.lua:121: 
[  script:qb-cityhall]  An error occurred while calling export `hireUser` in resource `qb-phone`:
[  script:qb-cityhall] 
[  script:qb-cityhall]  ---
```

Also when i use the "Setjob" command, the job never appears in the phone, even though i am employed:

![image](https://user-images.githubusercontent.com/96505896/196484173-d9bfe94b-70b6-421b-ac71-a8fc74a4050b.png)

Is there anything that i am missing? Jobs still work, and so do the commands, they just dont show in the phone app.

Thanks!

**Comment by django1m** [comment]
did you find a way to make it work ?

**Comment by Keohh** [comment]
Any fix?

**Comment by itsKline** [comment]
Be sure to follow the readme fully as you need to make edits to your qb-cityhall. Closing this issue as it is not an issue with our phone
