### ISSUE TITLE
(Question) - Groups exports

### ISSUE THREAD

**Issue by JAY-YZ** [Renewed-Scripts/qb-phone#77]
Has anyone got a example of how to take full advantage of the groups app to set the tasks and update each task ect just like the attached image below.

![image](https://user-images.githubusercontent.com/97201025/205158153-8adc2993-b20f-4ddc-9e36-81e702146ad5.png)

**Comment by itsKline** [comment]
For questions like this, please join the discord.

https://dsc.gg/Renewed
