### ISSUE TITLE
Bugs and Suggestions

### ISSUE THREAD

**Issue by Im-Kayun** [Renewed-Scripts/qb-phone#82]
Suggestion: 
Add Bank App to make it easier to transfer money and access accounts.
In the invoices application, in addition to the invoices show also fines.

Bugs:
Documents App: 

When switching to the "Documents" category, the name is not changed.

When I view a document and go back, it goes to the "Vehicle Registrations" category and should go back to the "Documents" category. 

When I view a license or vehicle registration, when I go back the records are not shown and I need to change categories to update.

When I create a new document it is not added to the category, only when I create another one is the previous one added. The title of the document is not deleted either

**Comment by itsKline** [comment]
For your suggestion, the wenmo app will be released eventually when Zoo has time to get it written and released
