### ISSUE TITLE
Few Jobs doesnt show up

### ISSUE THREAD

**Issue by rust1co** [Renewed-Scripts/qb-phone#83]
Probabily a bug on phone, when i do set my job in a existing character and it doesnt show up, i reset the server, set first start true , then open the server, in game i ensure the phone, alright, the job starts to show on Employment APP. 

But if i do create a new character and try to give the same job which was showing in last restart, it returns me this error. 

![image](https://user-images.githubusercontent.com/81710506/206979881-2feae766-6c07-48d4-9b92-7c932afc4dc5.png)

**Comment by Keohh** [comment]
did you find a fix for this?

**Comment by itsKline** [comment]
Seems like you did not follow the readme carefully. Or, this is an issue that was created before the grade 0 fix
