### ISSUE TITLE
Crypto "QBIT" not displaying under Crypto app.

### ISSUE THREAD

**Issue by mfjosh** [Renewed-Scripts/qb-phone#87]
It appears after switching from qb-phone to qb-phone from renewed scripts, the instructions for getting crypto to work does not include Qbit which is the one crypto used by qb-crypto. 

If this is not an issue, can anyone help me understand how to change qb-crypto to make the crypto's in the phone relevant?

**Comment by AlexGThess** [comment]
+1

**Comment by kronikjay** [comment]
looking for the answer to this as well. I can add Qbit under config but cannot get it to work with the crypto sticks that you use to hack at lesters house. it says its giving you qbit but no way to sell buy or trade them.

**Comment by SantaOfAnthrax** [comment]
Under the config file do this 
![image](https://user-images.githubusercontent.com/127038020/222969469-7915ced0-b100-4d31-93f4-40fc6e1cd8dc.png)
then under qb-core/server/player.lua under player.metadata where you put the stuff for the crypto do this 
![image](https://user-images.githubusercontent.com/127038020/222969550-4e10a8ab-e981-41f5-86d9-ae186ec5292a.png)

**Comment by SantaOfAnthrax** [comment]
> 

could you by chance put a pic of your qb-crypto/server/main.lua where you placed what you said above so i can see it?

**Comment by twigmasters** [comment]
Line 216-236 of qb-crypto/server/main.lua
`RegisterServerEvent('qb-crypto:server:ExchangeSuccess', function(LuckChance)
    local src = source
    local Player = QBCore.Functions.GetPlayer(src)
    local ItemData = Player.Functions.GetItemByName("cryptostick")

    if ItemData ~= nil then
        local LuckyNumber = math.random(1, 10)
        local DeelNumber = 1000000
        local Amount = (math.random(611111, 1599999) / DeelNumber)
        if LuckChance == LuckyNumber then
            Amount = (math.random(1599999, 2599999) / DeelNumber)
        end

        Player.Functions.RemoveItem("cryptostick", 1)
        local src = source
        exports['qb-phone']:AddCrypto(src, "gne", 5)
        TriggerClientEvent('QBCore:Notify', src, Lang:t('success.you_have_exchanged_your_cryptostick_for',{amount = Amount}), "success", 3500)
        TriggerClientEvent('inventory:client:ItemBox', src, QBCore.Shared.Items["cryptostick"], "remove")
        TriggerClientEvent('qb-phone:client:AddTransaction', src, Player, {},  Lang:t('credit.there_are_amount_credited',{amount = Amount}), "Credit")
    end
end)`
