### ISSUE TITLE
[BUG] Pause Menu coming up when pressing Escape to exit phone

### ISSUE THREAD

**Issue by SirOMGitsYOU** [Renewed-Scripts/qb-phone#88]
Hey - 

We have a custom pause menu ([RSD-PAUSEMENU](https://script.redstartrp.fr/)) - This combined with the AllowWalking config option, When pressing Escape to exit the phone, this will close down the phone while also bringing up the pause menu.

Is there anything that can be looked at to prevent the ESC option from opening the pause menu or just being locked to input on the phone with the allowwalking option on? As this doesn't happen with it off, but our player base loves this option.

**Comment by itsKline** [comment]
I would suggest making a check in your pausemenu to see if the phone is open. Another way would be to add a keypress to close the phone. Nonetheless, this is not a bug with our phone so this issue will be closed
