### ISSUE TITLE
vehicles app does not show vehicles

### ISSUE THREAD

**Issue by Donnyjohn1** [Renewed-Scripts/qb-phone#89]
![image](https://user-images.githubusercontent.com/104074220/210122141-d358d857-6d96-4655-97f0-85783415e20d.png)

**Comment by Donnyjohn1** [comment]
![image](https://user-images.githubusercontent.com/104074220/210123843-5be131a0-8ba0-4ab2-8f9d-a1bbd8670740.png)

**Comment by Donnyjohn1** [comment]
also breaks qb garages script

**Comment by Donnyjohn1** [comment]
im runnig the latest qb-garages

**Comment by HeyYuvraj** [comment]
> im runnig the latest qb-garages

**Headover to QB-Phone/server/garage.lua**

On line 56, Replace this block of code
```
            if v.garage then
                if Garages[v.garage] then
                    VehicleGarage = Garages[v.garage]["label"]
                else
                    VehicleGarage = v.garage
                end
            end
```

With this

```
            if v.garage then
                if Config.Garages[v.garage] then
                    VehicleGarage = Config.Garages[v.garage]["label"]
                else
                    VehicleGarage = v.garage
                end
            end
```

**Comment by itsKline** [comment]
Fixed in a previous update
