### ISSUE TITLE
job

### ISSUE THREAD

**Issue by FMGAMING3022** [Renewed-Scripts/qb-phone#90]
my job goes back to civilian, unemployed.

**Comment by Z3YR0XBG** [comment]
+1

**Comment by ryan1018** [comment]
same issue

**Comment by mspiggygaming** [comment]
no fix yet? :(

**Comment by blackalae** [comment]
my job goes back to civilian, unemployed.

**Comment by zSmilleey** [comment]
same

**Comment by ongLando** [comment]
What you do, is you go to qb-phone/server/employment.lua, and at line 27 the local FirstStart = false, set it to true. You're going to basically repeat the process from the readme, for employment. Do that, and restart the server. Then go into your server and make sure the phone works properly. Then what you are going to do, is do the same thing at qb-phone/server/employment.lua line 27 but change local FirstStart = true to false. Then restart the server again, set your job and it should work.

**Comment by ongLando** [comment]
> my job goes back to civilian, unemployed.


What you do, is you go to qb-phone/server/employment.lua, and at line 27 the local FirstStart = false, set it to true. You're going to basically repeat the process from the readme, for employment. Do that, and restart the server. Then go into your server and make sure the phone works properly. Then what you are going to do, is do the same thing at qb-phone/server/employment.lua line 27 but change local FirstStart = true to false. Then restart the server again, set your job and it should work.

**Comment by itsKline** [comment]
This is not an issue with the phone, please re-read the readme and follow it carefully
