### ISSUE TITLE
Stuck In Taking Photos

### ISSUE THREAD

**Issue by Blazzer10200** [Renewed-Scripts/qb-phone#96]
When I take a photo on the phone it says that I took the photo but im stuck in the camera forever I did all the steps put in the discord webhook for the photos still giving me a hard time no errors.

Here a preview
https://medal.tv/games/gta-v/clips/SVTEXmPqcMd7G/d1337vHNxCeJ?invite=cr-MSxDbmUsMjEyNzgzMTEs

**Comment by AlexGThess** [comment]
+1

**Comment by ryan1018** [comment]
same issue

**Comment by paruthepro** [comment]
Should be fixed, was an issue with the webhook.

**Comment by itsKline** [comment]
As said, this has been fixed. Was a discord issue.
