### ISSUE TITLE
Tracking vehicles

### ISSUE THREAD

**Issue by RekoXV** [Renewed-Scripts/qb-phone#97]
Tracking vehicles not working

**Comment by paruthepro** [comment]
Fixed in latest push :)

**Comment by SirOMGitsYOU** [comment]
> Fixed in latest push :)

Not working for me even on the latest version, just says it can’t find the vehicle

**Comment by itsKline** [comment]
We have had no issues. If the issue persists, please let us know in the discord.

https://dsc.gg/Renewed
